BEGIN;

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    full_name TEXT,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS sessions (
    token TEXT PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS ai_settings (
    id SMALLINT PRIMARY KEY CHECK (id = 1),
    provider TEXT NOT NULL,
    yandex_api_key_encrypted TEXT,
    yandex_folder_id TEXT,
    yandex_model_uri TEXT,
    group_processors_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    use_sync_start_date BOOLEAN NOT NULL DEFAULT FALSE,
    sync_start_date DATE,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS marketplace_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    marketplace TEXT NOT NULL,
    account_name TEXT NOT NULL,
    api_url TEXT NOT NULL,
    api_key_encrypted TEXT,
    extra_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS response_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    category TEXT NOT NULL,
    mode TEXT NOT NULL,
    is_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    template_text TEXT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    UNIQUE (user_id, category)
);

CREATE TABLE IF NOT EXISTS response_template_variants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    group_id TEXT NOT NULL,
    subgroup TEXT NOT NULL,
    template_text TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS default_template_variants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id TEXT NOT NULL,
    subgroup TEXT NOT NULL,
    template_text TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    UNIQUE (group_id, subgroup, template_text)
);

CREATE TABLE IF NOT EXISTS processing_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    group_id TEXT NOT NULL,
    action_mode TEXT NOT NULL,
    auto_send BOOLEAN NOT NULL DEFAULT FALSE,
    updated_at TIMESTAMPTZ NOT NULL,
    UNIQUE (user_id, group_id)
);

CREATE TABLE IF NOT EXISTS product_recommendations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    source_article TEXT NOT NULL,
    target_article TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    UNIQUE (user_id, source_article, target_article)
);

CREATE TABLE IF NOT EXISTS review_items (
    review_uid TEXT PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    external_review_id TEXT NOT NULL,
    source TEXT NOT NULL,
    account_id BIGINT REFERENCES marketplace_accounts(id) ON DELETE SET NULL,
    text TEXT NOT NULL,
    author TEXT,
    rating INTEGER,
    metadata_json JSONB NOT NULL,
    normalized_text TEXT NOT NULL,
    sentiment_score INTEGER NOT NULL,
    sentiment_label TEXT NOT NULL,
    is_spam BOOLEAN NOT NULL,
    is_toxic BOOLEAN NOT NULL,
    priority TEXT NOT NULL,
    tags_json JSONB NOT NULL,
    recommended_action TEXT NOT NULL,
    category TEXT NOT NULL,
    processing_mode TEXT NOT NULL,
    status TEXT NOT NULL,
    auto_reply TEXT,
    manual_reply TEXT,
    operator_name TEXT,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS review_actions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    review_uid TEXT,
    action_type TEXT NOT NULL,
    actor TEXT NOT NULL,
    details_json JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS conversation_items (
    conversation_uid TEXT PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    source TEXT NOT NULL,
    account_id BIGINT REFERENCES marketplace_accounts(id) ON DELETE SET NULL,
    external_conversation_id TEXT NOT NULL,
    kind TEXT NOT NULL,
    customer_name TEXT,
    message_text TEXT NOT NULL,
    status TEXT NOT NULL,
    unread_count INTEGER NOT NULL DEFAULT 0,
    metadata_json JSONB NOT NULL,
    send_error_code TEXT,
    send_error_message TEXT,
    send_attempts INTEGER NOT NULL DEFAULT 0,
    last_send_attempt_at TIMESTAMPTZ,
    last_sent_at TIMESTAMPTZ,
    last_message_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS conversation_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_uid TEXT NOT NULL REFERENCES conversation_items(conversation_uid) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    direction TEXT NOT NULL,
    message_text TEXT NOT NULL,
    operator_name TEXT,
    send_status TEXT NOT NULL DEFAULT 'sent',
    send_error_code TEXT,
    send_error_message TEXT,
    idempotency_key TEXT,
    external_message_id TEXT,
    created_at TIMESTAMPTZ NOT NULL,
    UNIQUE (user_id, conversation_uid, idempotency_key)
);

CREATE TABLE IF NOT EXISTS template_variables (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    var_key TEXT NOT NULL UNIQUE,
    title TEXT NOT NULL,
    description TEXT,
    is_user_editable BOOLEAN NOT NULL DEFAULT FALSE,
    source_type TEXT NOT NULL DEFAULT 'manual',
    source_path TEXT,
    default_value TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS user_template_variable_values (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    variable_id BIGINT NOT NULL REFERENCES template_variables(id) ON DELETE CASCADE,
    value TEXT,
    updated_at TIMESTAMPTZ NOT NULL,
    UNIQUE (user_id, variable_id)
);

CREATE INDEX IF NOT EXISTS idx_sessions_user_expires
    ON sessions(user_id, expires_at);

CREATE INDEX IF NOT EXISTS idx_accounts_user_active
    ON marketplace_accounts(user_id, is_active);

CREATE INDEX IF NOT EXISTS idx_template_variants_user_group_sub
    ON response_template_variants(user_id, group_id, subgroup, is_active);

CREATE INDEX IF NOT EXISTS idx_default_template_variants_group_sub
    ON default_template_variants(group_id, subgroup, is_active);

CREATE INDEX IF NOT EXISTS idx_processing_rules_user_group
    ON processing_rules(user_id, group_id);

CREATE INDEX IF NOT EXISTS idx_recommendations_user_source
    ON product_recommendations(user_id, source_article, is_active);

CREATE INDEX IF NOT EXISTS idx_review_actions_user_created
    ON review_actions(user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_conversation_user_updated
    ON conversation_items(user_id, updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_conversation_messages_conversation_created
    ON conversation_messages(conversation_uid, created_at ASC);

CREATE INDEX IF NOT EXISTS idx_template_variables_active
    ON template_variables(is_active, var_key);

CREATE INDEX IF NOT EXISTS idx_user_template_values_user
    ON user_template_variable_values(user_id, variable_id);

CREATE INDEX IF NOT EXISTS idx_review_items_user_updated
    ON review_items(user_id, updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_review_items_user_status_updated
    ON review_items(user_id, status, updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_review_items_user_source_updated
    ON review_items(user_id, source, updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_review_items_user_category_updated
    ON review_items(user_id, category, updated_at DESC);

INSERT INTO ai_settings (
    id, provider, yandex_api_key_encrypted, yandex_folder_id, yandex_model_uri,
    group_processors_json, use_sync_start_date, sync_start_date, updated_at
)
VALUES (
    1,
    'rules',
    NULL,
    NULL,
    NULL,
    '{"positive":"yandex","product_dissatisfaction":"yandex","delivery_problems":"yandex","wrong_size":"yandex","tagged_reviews":"program","textless_ratings":"program"}'::jsonb,
    FALSE,
    NULL,
    NOW()
)
ON CONFLICT (id) DO NOTHING;

COMMIT;
