-- Post-import validation script for SQLite -> PostgreSQL migration.
-- Usage:
-- psql "$APP_DB_URL" -f deploy/postgres/validation_after_import.sql
--
-- Note:
-- Compare row counts with SQLite export manifest.json generated by:
-- scripts/export_sqlite_for_postgres.py

\echo '=== Row counts ==='
SELECT 'users' AS table_name, COUNT(*) AS row_count FROM users
UNION ALL SELECT 'sessions', COUNT(*) FROM sessions
UNION ALL SELECT 'ai_settings', COUNT(*) FROM ai_settings
UNION ALL SELECT 'marketplace_accounts', COUNT(*) FROM marketplace_accounts
UNION ALL SELECT 'response_templates', COUNT(*) FROM response_templates
UNION ALL SELECT 'response_template_variants', COUNT(*) FROM response_template_variants
UNION ALL SELECT 'processing_rules', COUNT(*) FROM processing_rules
UNION ALL SELECT 'product_recommendations', COUNT(*) FROM product_recommendations
UNION ALL SELECT 'review_items', COUNT(*) FROM review_items
UNION ALL SELECT 'review_actions', COUNT(*) FROM review_actions
UNION ALL SELECT 'conversation_items', COUNT(*) FROM conversation_items
ORDER BY table_name;

\echo ''
\echo '=== Core uniqueness checks ==='
SELECT 'users.email duplicates' AS check_name, COUNT(*) AS issues
FROM (
    SELECT email FROM users GROUP BY email HAVING COUNT(*) > 1
) t
UNION ALL
SELECT 'review_items.review_uid duplicates', COUNT(*)
FROM (
    SELECT review_uid FROM review_items GROUP BY review_uid HAVING COUNT(*) > 1
) t
UNION ALL
SELECT 'conversation_items.conversation_uid duplicates', COUNT(*)
FROM (
    SELECT conversation_uid FROM conversation_items GROUP BY conversation_uid HAVING COUNT(*) > 1
) t
UNION ALL
SELECT 'processing_rules(user_id, group_id) duplicates', COUNT(*)
FROM (
    SELECT user_id, group_id FROM processing_rules GROUP BY user_id, group_id HAVING COUNT(*) > 1
) t;

\echo ''
\echo '=== Foreign key orphan checks ==='
SELECT 'sessions.user_id -> users.id' AS fk_name, COUNT(*) AS orphans
FROM sessions s
LEFT JOIN users u ON u.id = s.user_id
WHERE u.id IS NULL
UNION ALL
SELECT 'marketplace_accounts.user_id -> users.id', COUNT(*)
FROM marketplace_accounts a
LEFT JOIN users u ON u.id = a.user_id
WHERE u.id IS NULL
UNION ALL
SELECT 'response_templates.user_id -> users.id', COUNT(*)
FROM response_templates t
LEFT JOIN users u ON u.id = t.user_id
WHERE u.id IS NULL
UNION ALL
SELECT 'response_template_variants.user_id -> users.id', COUNT(*)
FROM response_template_variants t
LEFT JOIN users u ON u.id = t.user_id
WHERE u.id IS NULL
UNION ALL
SELECT 'processing_rules.user_id -> users.id', COUNT(*)
FROM processing_rules r
LEFT JOIN users u ON u.id = r.user_id
WHERE u.id IS NULL
UNION ALL
SELECT 'product_recommendations.user_id -> users.id', COUNT(*)
FROM product_recommendations p
LEFT JOIN users u ON u.id = p.user_id
WHERE u.id IS NULL
UNION ALL
SELECT 'review_items.user_id -> users.id', COUNT(*)
FROM review_items r
LEFT JOIN users u ON u.id = r.user_id
WHERE u.id IS NULL
UNION ALL
SELECT 'review_items.account_id -> marketplace_accounts.id', COUNT(*)
FROM review_items r
LEFT JOIN marketplace_accounts a ON a.id = r.account_id
WHERE r.account_id IS NOT NULL AND a.id IS NULL
UNION ALL
SELECT 'review_actions.user_id -> users.id', COUNT(*)
FROM review_actions a
LEFT JOIN users u ON u.id = a.user_id
WHERE u.id IS NULL
UNION ALL
SELECT 'conversation_items.user_id -> users.id', COUNT(*)
FROM conversation_items c
LEFT JOIN users u ON u.id = c.user_id
WHERE u.id IS NULL
UNION ALL
SELECT 'conversation_items.account_id -> marketplace_accounts.id', COUNT(*)
FROM conversation_items c
LEFT JOIN marketplace_accounts a ON a.id = c.account_id
WHERE c.account_id IS NOT NULL AND a.id IS NULL;

\echo ''
\echo '=== Data quality checks ==='
SELECT 'ai_settings exactly one row with id=1' AS check_name,
       CASE WHEN (SELECT COUNT(*) FROM ai_settings WHERE id = 1) = 1 THEN 0 ELSE 1 END AS issues
UNION ALL
SELECT 'invalid boolean-like statuses in review_items.status',
       COUNT(*)
FROM review_items
WHERE status IS NULL OR btrim(status) = ''
UNION ALL
SELECT 'invalid conversation kind',
       COUNT(*)
FROM conversation_items
WHERE kind NOT IN ('question', 'chat')
UNION ALL
SELECT 'invalid conversation status',
       COUNT(*)
FROM conversation_items
WHERE status NOT IN ('open', 'waiting', 'closed');

\echo ''
\echo '=== Deterministic checksums (table-level) ==='
-- Use md5 over stable ordered concatenations of key fields.
SELECT 'users' AS table_name,
       md5(COALESCE(string_agg(id::text || '|' || email || '|' || role || '|' || created_at::text, '||' ORDER BY id), '')) AS checksum
FROM users
UNION ALL
SELECT 'marketplace_accounts',
       md5(COALESCE(string_agg(id::text || '|' || user_id::text || '|' || marketplace || '|' || account_name || '|' || is_active::text, '||' ORDER BY id), ''))
FROM marketplace_accounts
UNION ALL
SELECT 'review_items',
       md5(COALESCE(string_agg(review_uid || '|' || user_id::text || '|' || source || '|' || status || '|' || updated_at::text, '||' ORDER BY review_uid), ''))
FROM review_items
UNION ALL
SELECT 'review_actions',
       md5(COALESCE(string_agg(id::text || '|' || user_id::text || '|' || action_type || '|' || created_at::text, '||' ORDER BY id), ''))
FROM review_actions
UNION ALL
SELECT 'conversation_items',
       md5(COALESCE(string_agg(conversation_uid || '|' || user_id::text || '|' || kind || '|' || status || '|' || updated_at::text, '||' ORDER BY conversation_uid), ''))
FROM conversation_items
ORDER BY table_name;
